### ISSUE TITLE
Build Error?

### ISSUE THREAD

**Issue by xloem** [mnzaki/processpace#2]
```
ERROR in ./src/views/index.jsx                                                                                                                                                   [0/138]
Module build failed: SyntaxError: Unexpected token {                                                                              
    at exports.runInThisContext (vm.js:53:16)         
    at Module._compile (module.js:373:25)                                                                               
    at Object.Module._extensions..js (module.js:416:10)                                                
    at Module.load (module.js:343:32)                                           
    at Function.Module._load (module.js:300:12)                                           
    at Module.require (module.js:353:17)                                                    
    at require (internal/module.js:12:17)                                           
    at loadLoader (/home/user/src/processpace/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/user/src/processpace/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/user/src/processpace/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
 @ ./src/index.js 5:0-34                                                                                                                        
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js                                  
```

**Comment by mnzaki** [comment]
hmmm the error is very vague, and I can't reproduce it of course.... 
Some basics first: is this a fresh install, you just ran `npm install` then `npm start`??
Some blind debugging tips: remove stuff from `index.jsx` until it compiles successfully, and figure out which line is actually causing the SyntaxError.
